---
    - name: install openjdk
      yum: name=java-1.8.0-openjdk-devel state=present
      
    - name: 01 add epel
      yum_repository:
       name: epel
       description: EPEL YUM repo
       baseurl: https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
      become: yes

    - name: 02 yum update 
      yum: name=* state=latest
  
    - name: download Jenkins repo
      get_url: 
          url: http://pkg.jenkins-ci.org/redhat-stable/jenkins.repo
          dest: /etc/yum.repos.d/jenkins.repo
 
    - name: import GPG key
      rpm_key: key=https://pkg.jenkins.io/redhat-stable/jenkins.io.key state=present
      
    - name: install Jenkins server
      yum: name=jenkins state=present

    - name: start jenkins service and enable on boot
      service: name=jenkins state=started enabled=yes

